Update utils.py line 576
update to line 576

image_path = get_image_path_from_stream(darwin_json, images_dir, with_folders = 0, annotation_filepath = annotation_path)

get_image_path_from_stream() command requires all 4 inputs. It does not work otherwise. This the error that arises:

TypeError: get_image_path_from_stream() missing 2 required positional arguments: 'with_folders' and 'annotation_filepath'